

NAME = ft_ls




all:
	gcc -I lib42 ft_ls.c lib42/options/ft_options.a lib42/libft/libft.a

debug:
	gcc -g -I lib42 ft_ls.c lib42/options/ft_options.a lib42/libft/libft.a

verbose:
	gcc -v -I lib42 ft_ls.c lib42/options/ft_options.a lib42/libft/libft.a
